# Generated by Django 4.1.7 on 2024-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0002_userassiocitionprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationuser',
            name='bankili_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='associationuser',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='associationuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='associationuser',
            name='whatsapp_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
