# Generated by Django 4.1.7 on 2024-03-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0006_associationuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationuser',
            name='another_image',
            field=models.ImageField(blank=True, null=True, upload_to='another_image/'),
        ),
    ]
