# Generated by Django 4.1.7 on 2024-03-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0007_associationuser_another_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationuser',
            name='image',
        ),
    ]
